Integration with RNAseq results

Download the DESeq2 results
  (GSE75070_MCF7_shRUNX1_shNS_RNAseq_log2_foldchange.txt.gz) and upload this
  file to the SCC.

In a jupyter notebook, apply the same filters and cutoffs as specified in
  the methods of the original paper. How many DE genes do you find? Do they
  match the numbers reported in the paper?

By applying the same filters, I observed 1227 genes at first. But upon checking the data, I realised it had some NA values. 
So upon removing these NA values, I was able to match the same number of upregulated and downregulated genes as mentioned in the paper. 
  
setwd ('/projectnb/bf528/students/jawa/project-2-jawa23bio/results')

data <- read.table("GSE75070_MCF7_shRUNX1_shNS_RNAseq_log2_foldchange.txt", header = TRUE)

# Filter the DE genes based on criteria
filtered_de_genes <- data[data$padj <= 0.01 & abs(data$log2FoldChange) > 1, ]
nrow(filtered_de_genes)

significant_de_genes <- na.omit(filtered_de_genes)
nrow(significant_de_genes)

# Filter upregulated genes (log2 fold change > 1)
upregulated_genes <- significant_de_genes[significant_de_genes$log2FoldChange > 1, ]
nrow(upregulated_genes)

# Filter downregulated genes (log2 fold change < -1)
downregulated_genes <- significant_de_genes[significant_de_genes$log2FoldChange < -1, ]
nrow(downregulated_genes)